export const INITIAL_PROJECTS = [
  {
    id: "PRJ-01",
    name: "NextGen Cloud Migration",
    category: "Infrastructure",
    description: "Multi-region AWS to GCP cluster migration with zero-downtime database sharding.",
    progress: 78,
    status: "On Track",
    statusColor: "emerald",
    lead: "Marcus Chen",
    leadAvatar: "MC",
    teamCount: 6,
    dueDate: "Oct 24, 2026",
    tasksTotal: 34,
    tasksCompleted: 27,
    budget: "$45,000",
  },
  {
    id: "PRJ-02",
    name: "Stripe Recurring Billing & Tax",
    category: "Fintech",
    description: "Automated recurring SaaS subscriptions, webhook idempotency, and EU VAT calculation.",
    progress: 62,
    status: "On Track",
    statusColor: "emerald",
    lead: "Elena Rostova",
    leadAvatar: "ER",
    teamCount: 4,
    dueDate: "Nov 02, 2026",
    tasksTotal: 22,
    tasksCompleted: 14,
    budget: "$28,000",
  },
  {
    id: "PRJ-03",
    name: "Autonomous AI Copilot Engine",
    category: "AI & ML",
    description: "Multi-agent LLM reasoning pipeline with vector memory and automated backlog synthesis.",
    progress: 89,
    status: "On Track",
    statusColor: "cyan",
    lead: "Alex Morgan",
    leadAvatar: "AM",
    teamCount: 8,
    dueDate: "Oct 18, 2026",
    tasksTotal: 48,
    tasksCompleted: 43,
    budget: "$60,000",
  },
  {
    id: "PRJ-04",
    name: "Mobile App v2.4 Release",
    category: "Mobile",
    description: "React Native performance overhaul with biometric authentication and offline CRDT sync.",
    progress: 41,
    status: "At Risk",
    statusColor: "amber",
    lead: "David Kim",
    leadAvatar: "DK",
    teamCount: 5,
    dueDate: "Nov 15, 2026",
    tasksTotal: 30,
    tasksCompleted: 12,
    budget: "$32,000",
  },
];

export const INITIAL_TASKS = [
  {
    id: "TK-101",
    title: "Synthesize Auth 2.0 OIDC Handlers & Session Tokens",
    project: "Autonomous AI Copilot Engine",
    assignee: "Alex Morgan",
    avatar: "AM",
    tag: "Security",
    priority: "Urgent",
    column: "inprogress",
    points: 5,
    dueDate: "Tomorrow",
    comments: 4,
  },
  {
    id: "TK-102",
    title: "WebGL 3D State Rendering Pipeline & GPU Disposal",
    project: "Autonomous AI Copilot Engine",
    assignee: "Marcus Chen",
    avatar: "MC",
    tag: "Frontend",
    priority: "High",
    column: "inprogress",
    points: 8,
    dueDate: "Oct 12",
    comments: 7,
  },
  {
    id: "TK-103",
    title: "Sub-50ms CRDT Sync Consensus Engine",
    project: "NextGen Cloud Migration",
    assignee: "Elena Rostova",
    avatar: "ER",
    tag: "Distributed",
    priority: "Urgent",
    column: "review",
    points: 5,
    dueDate: "Oct 10",
    comments: 12,
  },
  {
    id: "TK-104",
    title: "Stripe Webhook Idempotency Key Validation",
    project: "Stripe Recurring Billing & Tax",
    assignee: "Elena Rostova",
    avatar: "ER",
    tag: "Backend",
    priority: "High",
    column: "review",
    points: 3,
    dueDate: "Oct 11",
    comments: 2,
  },
  {
    id: "TK-105",
    title: "Design System Dark/Light Theme Token Architecture",
    project: "Mobile App v2.4 Release",
    assignee: "Priya Sharma",
    avatar: "PS",
    tag: "UI/UX",
    priority: "Medium",
    column: "todo",
    points: 3,
    dueDate: "Oct 16",
    comments: 1,
  },
  {
    id: "TK-106",
    title: "Setup Redis Caching Layer for AI Embeddings",
    project: "Autonomous AI Copilot Engine",
    assignee: "Marcus Chen",
    avatar: "MC",
    tag: "Database",
    priority: "High",
    column: "todo",
    points: 5,
    dueDate: "Oct 14",
    comments: 3,
  },
  {
    id: "TK-107",
    title: "Air-Gapped Private VPC Helm Charts & K8s Config",
    project: "NextGen Cloud Migration",
    assignee: "Alex Morgan",
    avatar: "AM",
    tag: "DevOps",
    priority: "Medium",
    column: "backlog",
    points: 8,
    dueDate: "Oct 22",
    comments: 0,
  },
  {
    id: "TK-108",
    title: "Telemetry DORA Cycle-Time Aggregator Daemon",
    project: "NextGen Cloud Migration",
    assignee: "David Kim",
    avatar: "DK",
    tag: "Analytics",
    priority: "Low",
    column: "backlog",
    points: 5,
    dueDate: "Oct 28",
    comments: 0,
  },
  {
    id: "TK-109",
    title: "Automated Cypress E2E Checkout Flow Test Suite",
    project: "Stripe Recurring Billing & Tax",
    assignee: "David Kim",
    avatar: "DK",
    tag: "Testing",
    priority: "Medium",
    column: "done",
    points: 3,
    dueDate: "Completed",
    comments: 5,
  },
  {
    id: "TK-110",
    title: "Biometric Passkey Authentication for iOS/Android",
    project: "Mobile App v2.4 Release",
    assignee: "Priya Sharma",
    avatar: "PS",
    tag: "Mobile",
    priority: "High",
    column: "done",
    points: 5,
    dueDate: "Completed",
    comments: 9,
  },
];

export const INITIAL_TEAM = [
  {
    id: "USR-01",
    name: "Alex Morgan",
    role: "Lead Architect",
    email: "alex.morgan@taskaura.dev",
    avatar: "AM",
    status: "Active",
    workload: 85,
    activeTasks: 4,
    completedTasks: 38,
    badgeColor: "cyan",
  },
  {
    id: "USR-02",
    name: "Elena Rostova",
    role: "Senior Backend Engineer",
    email: "elena.r@taskaura.dev",
    avatar: "ER",
    status: "In Code Review",
    workload: 92,
    activeTasks: 5,
    completedTasks: 44,
    badgeColor: "emerald",
  },
  {
    id: "USR-03",
    name: "Marcus Chen",
    role: "Staff Cloud Engineer",
    email: "marcus.c@taskaura.dev",
    avatar: "MC",
    status: "Active",
    workload: 70,
    activeTasks: 3,
    completedTasks: 29,
    badgeColor: "indigo",
  },
  {
    id: "USR-04",
    name: "Priya Sharma",
    role: "Lead Product Designer",
    email: "priya.s@taskaura.dev",
    avatar: "PS",
    status: "Focus Mode",
    workload: 65,
    activeTasks: 3,
    completedTasks: 31,
    badgeColor: "pink",
  },
  {
    id: "USR-05",
    name: "David Kim",
    role: "Quality & Systems Engineer",
    email: "david.k@taskaura.dev",
    avatar: "DK",
    status: "Active",
    workload: 55,
    activeTasks: 2,
    completedTasks: 26,
    badgeColor: "amber",
  },
];

export const INITIAL_BLOCKERS = [
  {
    id: "BLK-01",
    repo: "taskaura/core-api",
    title: "PR #204 (gRPC Gateway) awaiting security audit review",
    impact: "Blocking 3 downstream auth sprint tasks",
    severity: "Urgent",
    resolved: false,
  },
  {
    id: "BLK-02",
    repo: "taskaura/webgl-engine",
    title: "WebGL shader memory leak on mobile viewport resize",
    impact: "Causes 12 FPS drop on mobile Safari",
    severity: "High",
    resolved: false,
  },
  {
    id: "BLK-03",
    repo: "taskaura/billing-service",
    title: "Stripe webhook signature timestamp clock drift test",
    impact: "Flaky test in continuous integration pipeline",
    severity: "Medium",
    resolved: false,
  },
];

export const INITIAL_NOTIFICATIONS = [
  {
    id: "NTF-01",
    type: "task",
    title: "Elena Rostova marked TK-103 as Ready for Review",
    time: "4 minutes ago",
    unread: true,
  },
  {
    id: "NTF-02",
    type: "ai",
    title: "AI Sentinel: Sprint 4 velocity on track for early delivery",
    time: "28 minutes ago",
    unread: true,
  },
  {
    id: "NTF-03",
    type: "project",
    title: "Marcus Chen updated NextGen Cloud Migration milestones",
    time: "2 hours ago",
    unread: true,
  },
  {
    id: "NTF-04",
    type: "system",
    title: "SOC-2 automated telemetry compliance scan passed 100%",
    time: "5 hours ago",
    unread: false,
  },
];

export const CALENDAR_EVENTS = [
  { id: "EV-01", day: 9, title: "Sprint 4 Mid-Sprint Review", type: "sprint", time: "10:00 AM" },
  { id: "EV-02", day: 12, title: "NextGen Cloud Canary Release", type: "deploy", time: "2:30 PM" },
  { id: "EV-03", day: 16, title: "Stripe Billing Production Cutover", type: "milestone", time: "11:00 AM" },
  { id: "EV-04", day: 20, title: "Mobile v2.4 Feature Freeze", type: "deadline", time: "5:00 PM" },
  { id: "EV-05", day: 24, title: "Quarterly Architecture Retrospective", type: "sprint", time: "4:00 PM" },
];
